### ISSUE TITLE
Picker not working

### ISSUE THREAD

**Issue by thestonebro** [jeremybarbet/react-native-portalize#1]
In the portal a react native picker does not update its value.

    "react-native-portalize": "^1.0.1",

when i use the official callstack-paper component it works.

![ezgif-3-e2f6f5d2d4e6 (1)](https://user-images.githubusercontent.com/58907519/80314545-6e43e480-87f2-11ea-9434-4364a268e15f.gif)

**Comment by jeremybarbet** [comment]
Hi!

Would you able to reproduce this issue with a [snack](https://snack.expo.io/), it's hard to see like this what could be the issue?

**Comment by thestonebro** [comment]
https://snack.expo.io/@jowagner/picker

**Comment by jeremybarbet** [comment]
Hi, it should be fixed now, could you try with version `1.0.3`
