### ISSUE TITLE
Error: getRandomValues() not supported

### ISSUE THREAD

**Issue by edc123** [jeremybarbet/react-native-portalize#10]
Affects `1.0.6` - upon launching app, I see the following error:

<img width="539" alt="Screen Shot 2020-08-18 at 12 54 24 am" src="https://user-images.githubusercontent.com/246438/90410170-5f5ca700-e0ed-11ea-9b52-db7752cffadc.png">

In my use case, I have some screens where I have two instances of Modalize - in other screens just one.

This issue can be fixed by the developer by following the steps at: https://github.com/uuidjs/uuid#getrandomvalues-not-supported as a polyfill is required for `uuid` to work in RN

Related to the fix in #9, which was a PR originally created to fix #7

**Comment by harveyappleton** [comment]
@jeremybarbet sad times, this is arising from the UUID implementation - as @edc123 rightly pointed out, we can also include this polyfill and all our problems go away.. only downside is adding this additional dependency, and it also requires cocoa pods on iOS. Whats your thoughts? Happy to do another PR with it included if you think thats best route :-)

**Comment by jeremybarbet** [comment]
Fix released in `1.0.7`
