### ISSUE TITLE
Children not properly cleaned on unmount

### ISSUE THREAD

**Issue by mavarazy** [jeremybarbet/react-native-portalize#3]
This is caused by an error in `Consumer` - key is undefined inside the useEffect.
Solution would be to `useRef` instead of `useState`.

Here is a video with more details

https://www.loom.com/share/3152178816fe4c58a17962128dd4e18a

**Comment by jeremybarbet** [comment]
Cf https://github.com/jeremybarbet/react-native-portalize/pull/4
