### ISSUE TITLE
react-native-modalize

### ISSUE THREAD

**Issue by SmirnovM91** [jeremybarbet/react-native-portalize#5]
I have 2 (react-navigation 5) screens which wrapped by your  <Host> component
- List
- Details

and one component <ModalReject/> which is 
```
<Portal >
        <Modalize
          modalStyle={[styles.modal]}
          adjustToContentHeight={true}
          FooterComponent={
            <Button
              disabled={this.reject_message.length === 0}
              text="SEND"
              onPress={this.onPress}
              style={styles.btn}
            />
          }
          HeaderComponent={<Text style={styles.menuTitle}>{title}</Text>}
          ref={this.modal}>
          <Input
            name="reject_message"
            onChangeText={this.onChange}
            label={t('ENTER_REASON')}
            type="simple"
            multiline
            numberOfLines={3}
            value={this.reject_message}
          />
        </Modalize>
      </Portal>
```
The <ModalReject/> is placed on each screens (List,Details).

1. open modal on List screen
2. navigate to Details screen
3. open modal on Details screen
4. go back to List screen and try to open modal again, and it is not showing

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/32675072/88576230-ec6c8d00-d066-11ea-9072-306ed3d0710a.gif)

**Comment by edc123** [comment]
Yeah - I am investigating something similar currently: logging our the ref's for each Modalize, I see that the _ref.current_ is `null`

**Comment by jeremybarbet** [comment]
Are you using the latest version: `1.0.4`? If so, is it also happening when using the previous version `1.0.3`?

**Comment by edc123** [comment]
Aha! Yes - can confirm the issue is not reproducible after downgrading to v1.0.3, will use that for now.

More info on my scenario is that I have two screens, each using `<Portal>` and `<Modalize>` - but switching between screens once (and for me, I have to minimize the app in Simulator) and triggering `Modalize.open()` results in the error.

**Comment by jeremybarbet** [comment]
Should be fixed in `1.0.5`. Let me know

**Comment by edc123** [comment]
looks good after 1.0.5 -- legend! 👍🏼

**Comment by jeremybarbet** [comment]
@benjaminreid is the legend!

**Comment by fukemy** [comment]
hi @SmirnovM91 , can u tell me which lib is your segment?
